name: Build TIPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Theos
        run: |
          # Cách cài này không cần tải SDKs về (tránh lỗi tar), 
          # nó dùng luôn SDKs có sẵn trên máy Mac ảo
          export THEOS=/opt/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          # Cài ldid
          brew install ldid
      - name: Build Tweak
        run: |
          export THEOS=/opt/theos
          make clean
          make package FINALPACKAGE=1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tipa-file
          path: |
            .theos/_
            *.deb
