name: Build TIPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/elihwyma/Theos/master/bin/install-theos)"
          echo "THEOS=/opt/theos" >> $GITHUB_ENV

      - name: Install ldid
        run: brew install ldid

      - name: Build Tweak
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tipa-file
          path: |
            .theos/_
            *.deb
