name: Build TIPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Theos
        run: |
          THEOS="$GITHUB_WORKSPACE/theos"
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          git clone --recursive https://github.com/theos/theos.git $THEOS
          brew install ldid
      - name: Build App using Theos
        run: |
          export THEOS="$GITHUB_WORKSPACE/theos"
          export THEOS_PACKAGE_SCHEME=iphone/tweak
          make clean
          make package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tipa-file
          path: |
            .theos/_
            *.deb
            *.tipa
